# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.test.com:
    container_name: orderer.test.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/test.com/orderers/orderer.test.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/test.com/orderers/orderer.test.com/tls/:/var/hyperledger/orderer/tls
    - orderer.test.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    

  peer0.benz.test.com:
    container_name: peer0.benz.test.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.benz.test.com
      - CORE_PEER_ADDRESS=peer0.benz.test.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.benz.test.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.benz.test.com:7051
      - CORE_PEER_LOCALMSPID=benzMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/benz.test.com/peers/peer0.benz.test.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/benz.test.com/peers/peer0.benz.test.com/tls:/etc/hyperledger/fabric/tls
        - peer0.benz.test.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer0.audi.test.com:
    container_name: peer0.audi.test.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.audi.test.com
      - CORE_PEER_ADDRESS=peer0.audi.test.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.audi.test.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.audi.test.com:7051
      - CORE_PEER_LOCALMSPID=audiMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/audi.test.com/peers/peer0.audi.test.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/audi.test.com/peers/peer0.audi.test.com/tls:/etc/hyperledger/fabric/tls
        - peer0.audi.test.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

